---
- name: upload kubeadm-config to /etc/kubernetes
  template:
    src: kubeadm-config.yaml.j2
    dest: /etc/kubernetes/kubeadm-config.yaml
    mode: 644
- name: initial kubeadmin
  command: kubeadm init --config=/etc/kubernetes/kubeadm-config.yaml --upload-certs
  notify: "restart kubelet service"
- name: setup kubeconfig for default user
  include_tasks: setup_kubeconfig.yml
- name: install calico pod network
  become: true
  become_user: "{{ default_user }}"
  command: kubectl apply -f https://docs.projectcalico.org/v3.8/manifests/calico.yaml
- name: get join command
  command: kubeadm token create --print-join-command
  register: join_command
- name: get join CertificateKey
  command: kubeadm init phase upload-certs --upload-certs
  register: join_CertificateKey
- name: copy join master command to local file
  local_action: copy content="{{ join_command.stdout_lines[0] }} --control-plane --certificate-key {{ join_CertificateKey.stdout_lines[-1] }}" dest="./join-master-command"
- name: copy join worker command to local file
  local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-worker-command"