---
- name: create directory of store kubeconfig for default user
  file:
    path: /home/{{ default_user }}/.kube
    state: directory
    owner: "{{ default_user }}"
    group: "{{ default_user }}"
    mode: '0755'
- name: copy kubeconfig for default user
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/{{ default_user }}/.kube/config
    owner: "{{ default_user }}"
    group: "{{ default_user }}"
    mode: '0644'
    remote_src: yes