---
- name: kubeadmin join as worker
  command: "{{ join_command + ' --apiserver-advertise-address=' + ansible_all_ipv4_addresses[0] }}"
  vars:
    join_command: "{{ lookup('file', './join-worker-command') }}"
  notify: "restart kubelet service"